### ISSUE TITLE
lost SIDEBAR title with 1.0.0

### ISSUE THREAD

**Issue by 7069wrk** [WebBreacher/obsidian-osint-templates#6]
I see that there are paths that have mods specific for 1.0 - wondering if the vertical title was one of those things we lost in 1.0.

i have downloaded 2 times as well as moved to a new copy of the template still no vertical title. 

i have played with the CSS but best i get is flipping the title around in the horizantal bar

![image](https://user-images.githubusercontent.com/102612356/197595562-c0ce835f-50e6-43bc-bf1e-2535c8de701c.png)

**Comment by 7069wrk** [comment]
i got really used to this being on the left and now all my notes have 2 titles and the header.   its going to be a mess to clean up. i am new to obsidian and used Micha;s OSINT stuff so as you can imagine im in a mess.    

thank you for any insight.   if not fixable i can just start a new vault and not use fancy stuff. LOL!

**Comment by WebBreacher** [comment]
Hi there. Yes, the Sliding Panes was removed in v1.0.0 of Obsidian. I've updated this repository to be compliant with v1.0.0 of the application. 

I'm very sorry that it has caused issues in your vault and you probably should not be using the live GitHub content directly as your vault. Instead, download the templates and copy them to another directory outside of GiThub's control. That way, when I update the templates, you choose if you update your vault or not. Don't want my changes to overwrite some important data in your working vault.

Hope this helps or, at least, explains it.

**Comment by 7069wrk** [comment]
hi,

no ones fault but mine. i saw the updates and copied to my vault location after upgrading my obsidian to 1.x. it wasnt until that upgrade that i saw any issues.

i have removed the sliding pane but my only remaining issue is that i just need to remove the second title. what has happened is that the title (in red box below) used to be in the side bar. now it moved to top of note in the place where it is by default but i the title was auto populated when note named and just need to remove second title from all notes in vault.

its just a maintenance thing i need to do and will do as i go back to each note.

Just wanted to check in and see if maybe there was a known bug that was fixable.

thank you for your time and talents shared to all of us. have a great day
[image.png]

Sent with [Proton Mail](https://proton.me/) secure email.

------- Original Message -------

**Comment by WebBreacher** [comment]
Your image got removed before it got to GitHub.

I think the second title is actually the file name as it is in a different place now and looks like a heading. You might want to try out different themes to see if you can make Obsidian look the way you desire. Good luck. Closing issue.
