### ISSUE TITLE
Community

### ISSUE THREAD

**Issue by Seandebasti** [WebBreacher/obsidian-osint-templates#7]
Hi, thanks for the template.
I like to try your repo. 
Is the Discord or the channel url still working, because I cannot rech it.
Thanks

PS: I found thisone via help, so you might change it in ther repo; https://obsidian.md/community

**Comment by WebBreacher** [comment]
Thanks for catching this. The OSINT Curious Discord has now been rebranded and the current link doesn't work. I'll replace it.
